Alterações nas abas home, equipe, projeto, processo seletivo e FAQ
pet-ads/homepage-pet-qui pull request #4
Opened 2024-07-10 22:12 UTC by GuilhermeAMendes

2024-07-10 23:28 UTC, fleurspirituelles requested changes
Guilherme, ótimo trabalho nas alterações das páginas! Neste review sugeri apenas modificações estéticas e que não afetam a funcionalidade. Excelente trabalho! 😊

2024-07-10 23:28 UTC, fleurspirituelles commented on build/index.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/LogoPETicone.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" con
Podemos aproveitar para substituir alguns dados da página de referência para os da página final, modificando `<meta name="description" content="Página do grupo PET/ADS do IFSP São Carlos"/>` para algo como `<meta name="description" content="Página do grupo PETSRTQUI do IFSP Sertãozinho"/>`.

2024-07-10 23:28 UTC, fleurspirituelles commented on src/pages/Equipe/SubComponentes/Card_Integrantes/CardAluno.js
Podemos aproveitar aqui também para atualizar as descrições das imagens da página de referência para a página oficial, modificando `var altFoto = "Foto de ${nome}, integrante do PET ADS do IFSP Sao Carlos";` para informações corretas de programa e tipo de integrante.

2024-07-10 23:28 UTC, fleurspirituelles commented on src/pages/Equipe/SubComponentes/Card_Integrantes/CardExAlunos.js
>    var altFoto = `Foto de ${nome}, Ex integrante do PET ADS do IFSP Sao Carlos`;
Podemos aproveitar aqui também para atualizar as descrições das imagens da página de referência para a página oficial, modificando `var altFoto = "Foto de ${nome}, Ex integrante do PET ADS do IFSP Sao Carlos";` para informações corretas de programa e tipo de integrante.

2024-07-10 23:28 UTC, fleurspirituelles commented on src/pages/Equipe/SubComponentes/Card_Integrantes/CardExTutores.js
>    var altFoto = `Foto de ${nome}, integrante do PET ADS do IFSP Sao Carlos`;
Podemos aproveitar aqui também para atualizar as descrições das imagens da página de referência para a página oficial, modificando `var altFoto = "Foto de ${nome}, integrante do PET ADS do IFSP Sao Carlos";` para informações corretas de programa e tipo de integrante.

2024-07-10 23:28 UTC, fleurspirituelles commented on src/pages/Equipe/SubComponentes/Card_Integrantes/CardTutor.js
Podemos aproveitar aqui também para atualizar as descrições das imagens da página de referência para a página oficial, modificando `var altFoto = "Foto de ${nome}, integrante do PET ADS do IFSP Sao Carlos";` para informações corretas de programa e tipo de integrante.

2024-07-11 14:14 UTC, GuilhermeAMendes commented
As alterações aplicadas com sucesso no último commit.

2024-07-11 14:14 UTC, merged